window.RESOURCE_DATA = [
  {id:1, category:'书单 / 文章 / 课程', title:'LLM 底层技术原理入门指南', url:'https://s3tlxskbq3.feishu.cn/docx/NyPqdCKraoXz9gxNVCfcIFdnnAc', summary:'非技术背景也能跟上的 LLM 原理学习路径。', audience:'非技术背景 / AI 入门', problem:'想系统理解 LLM 底层原理，却不知道从哪里开始。', reason:'访问人数12w+的一份 LLM 底层技术原理入门指南！作者是非技术背景，有学习路径指引+高亮标注，特别适合每日一读', contributor:'Carly · 京东 · AI 产品', tags:['LLM','学习路径'], updatedAt:'2026-08-02', score:95},
  {id:2, category:'职场成长 / 互助经验', title:'谈薪 Skill', url:'https://github.com/Ssupercoder/Salary-Negotiation-Skill/tree/main', summary:'把 Offer 解析、市场锚点和谈判话术放进一个 AI 咨询系统。', audience:'职场人 / 求职者', problem:'信息碎片化、谈判经验缺失，面对 Offer 不知道如何开口。', reason:'深夜收到Offer的那一刻，你盯着薪酬数字反复权衡——开口争取怕失去机会，沉默接受又不甘心折价。信息碎片化、辅导价格高昂、谈判经验缺失，构成了职场人谈薪时的三重结构性困境，本质上是一场信息不对称下的博弈劣势。\n我们构建的AI谈薪咨询系统（谈薪skill），基于LLM Agent架构与多模态理解能力，将谈薪从简单的"市场信息查询"升级为"专业化谈判策略咨询"。系统支持语音、PDF及文本多模态输入，通过级联意图识别与谈薪五阶段状态引擎，动态生成个性化博弈策略与标准化话术卡片；底层融合薪酬结构向量库、公司政策知识图谱及市场锚点数据，确保每一条建议都有据可依。从Offer解析到策略输出，全程可控、可验证、可复用。\n适合所有需要谈薪和职业规划的人', contributor:'玖月 · 智谱 · PE', tags:['Agent','职场'], updatedAt:'2026-08-02', score:92},
  {id:3, category:'职场成长 / 互助经验', title:'策略AI产品轩廷', url:'', links:[], summary:'大厂产品人分享策略、AI 与商业化的系统实践。', audience:'AI 产品 / 商业化新人', problem:'刚进入 AI、策略或商业化领域，缺少高质量的学习样本。', reason:'大厂多年产品人，在众多xhs博主中是我遇到的质量最高的一档，可以帮助新学习ai、策略、商业化的朋友系统了解', contributor:'耶耶 · 腾讯 · AI/商业化 PM', tags:['策略','商业化'], updatedAt:'2026-08-02', score:87},
  {id:4, category:'书单 / 文章 / 课程', title:'The AI Revolution: The Road to Superintelligence', url:'https://zhuanlan.zhihu.com/p/19950456', summary:'一篇来自 2015 年的 AGI 预测，回看超级智能叙事如何形成。', audience:'AI 观察者 / 产品人', problem:'想理解 ChatGPT 之前人们如何判断 AGI 与技术奇点。', reason:'因为这篇文章在2015年预测了2025-2030年的AGI智能奇点，可以看到前ChatGPT时代人对AGI的展望。', contributor:'小水 · OPPO · AIGC 产品', tags:['AGI','趋势'], updatedAt:'2026-08-02', score:82},
  {id:5, category:'书单 / 文章 / 课程', title:'WaytoAGI AI 知识库', url:'https://www.waytoagi.com/zh', summary:'面向非技术背景的 AI 实践知识库与资讯入口。', audience:'非技术背景 / AI 实践者', problem:'知道 AI 很重要，但缺少可以直接照着做的经验和入口。', reason:'这个平台适合所有非技术背景，但是想去尝试在技术里使用ai的人。我自己就是在这个平台上出了大量关于实际上使用的一些经验！并且可以持续了解最新的ai资讯', contributor:'shirley · 阿里 · AI 产品', tags:['知识库','实践'], updatedAt:'2026-08-02', score:91},
  {id:6, category:'书单 / 文章 / 课程', title:'从 0 看懂 RL', url:'https://ncns7qa5ozhl.feishu.cn/wiki/CWJQwm80KiMvhpksKL2c3KxVnVc?from=from_copylink', summary:'给 AI 产品经理的强化学习入门，连接训练方法与业务应用。', audience:'AIPM / 模型层产品', problem:'对训练方法一知半解，不知道如何在业务中应用。', reason:'现在越来越多的非技术背景同学在涌入aipm赛道，特别是模型层产品，最近发现很多时候看起来对训练方法有个认知，但实际上还是一知半解，且不知道在实际业务中如何应用，这篇文章能有效帮助解决上面问题', contributor:'pablo · 字节跳动 · AI PM', tags:['RL','模型'], updatedAt:'2026-08-02', score:88},
  {id:7, category:'其他', title:'小红书 Build in Public 分享', url:'https://xhslink.cn/m/AMzpgsvMOrh', summary:'一组关于 AI 与职场感想的公域利他分享。', audience:'希望获得灵感的实践者', problem:'遇到同类问题时，缺少真实、可参考的公开实践。', reason:'公域的利他分享，有点像zara的build in public，能给碰到同样问题的朋友一些启发', contributor:'荀檀', tags:['AI','经验分享'], updatedAt:'2026-08-02', score:79},
  {id:8, category:'行业动态 / 趋势观察', title:'北森 AI 面试官实战指南', url:'https://pan.baidu.com/s/1iREGA27ogeSrcbJNuGudXA?pwd=3A8r', summary:'从案例看 AI 面试官如何参与初筛与群面。', audience:'HR / 招聘产品 / 人力 Agent 团队', problem:'简历筛选慢、面试标准不统一、人力成本高。', reason:'这个文件展示了AI面试官如何替代初筛/群面环节，解决简历量大筛选慢、面试标准不统一、人力成本高、候选人体验差等痛点，帮助企业实现招聘提效降本与精准识人。如果有在做人力资源方向agent的朋友可以作为参考。', contributor:'珈珈', tags:['招聘','Agent'], updatedAt:'2026-08-02', score:84},
  {id:9, category:'产品功能 / 产品灵感', title:'浏览器自动化工具组合', url:'https://github.com/samlaying/browser-harness', links:[{label:'browser-harness：浏览器抓取与页面适配',url:'https://github.com/samlaying/browser-harness'},{label:'boss-agent：BOSS 直聘自动投递',url:'https://github.com/samlaying/boss-agent'},{label:'AI native 产品知识库',url:'https://pcnlp18cy9bm.feishu.cn/drive/folder/OXP3fNF8DlqN0WdjVOicmfYkNsF'}], summary:'浏览器抓取、页面适配与招聘自动化的开源工具组合。', audience:'产品经理 / 自动化实践者', problem:'需要获取浏览器信息，或根据简历和 JD 自动完成招聘动作。', reason:'1.爬取小红书&浏览器任何页面的skill：https://github.com/samlaying/browser-harness\n2.boss直聘ai 自动投递和打招呼浏览器插件：https://github.com/samlaying/boss-agent\n3.ai native 产品可以了解到知识库：https://pcnlp18cy9bm.feishu.cn/drive/folder/OXP3fNF8DlqN0WdjVOicmfYkNsF\n\n1.第一个是适合任何想要去获取浏览器信息，以及自动化操作的工具，在官方的基础上，目前增加了有小红书、X的页面适配器：\n2.这二个用来详细根据自己的简历以及JD自动去打招呼，为了防治被封，加了几个延迟\n3.自行整理的，用来去了解AI native产品所需要，可能需要了解的任何事情，从基础打造一个认知：', contributor:'山河 · 互联网 · 产品', tags:['浏览器','自动化'], updatedAt:'2026-08-02', score:86},
  {id:10, category:'小而美 App / 生活方式', title:'Parallels Desktop 11', url:'', links:[], summary:'Mac 上的虚拟机方案，用隔离环境兼容 Windows 软件。', audience:'Mac 用户 / 受设备策略限制的职场人', problem:'公司电脑限制安装软件，但工作又需要兼容 Windows 应用。', reason:'推荐个mac的vm 虚拟机。在公司有限制不能登录微信或其他软件的时候，走虚拟机端口，直接可以做数据转发，公司电脑不让下wx，管我虚拟机什么事【狗头', contributor:'铭赫', tags:['Mac','效率'], updatedAt:'2026-08-02', score:74},
  {id:11, category:'书单 / 文章 / 课程', title:'DeerFlow × AI Agent Book', url:'https://github.com/bytedance/deer-flow', links:[{label:'DeerFlow：字节跳动 harness 框架',url:'https://github.com/bytedance/deer-flow'},{label:'AI Agent Book：工程原理导读',url:'https://github.com/bojieli/ai-agent-book'}], summary:'从 harness 框架到工程原理导读，适合边学边做 Agent。', audience:'Agent 初学者 / AI 工程实践者', problem:'对 Agent 不熟悉，想从原理走到可运行 Demo。', reason:'两者资源相结合，可以帮助还未接触AI或对Agent不熟悉的同学，建立扎实的认知，并可根据开源框架自己搓demo实践，同时提供了原理导读以及实践范例，方便同学们实践出真知，在ai时代不断学习成长', contributor:'杨星 · 字节 · AI', tags:['Agent','开源'], updatedAt:'2026-08-02', score:93},
  {id:12, category:'书单 / 文章 / 课程', title:'从存在主义到纳瓦尔的主题书单', url:'', links:[], summary:'一套围绕意义、周期、制度与杠杆的长期阅读框架。', audience:'职业迷茫 / 长期主义者', problem:'焦虑、迷茫，想重新建立思考、行动和反馈系统。', reason:'迷茫焦虑一代人的意义创造和内核的重塑。人类存在的本质和未来、人本与生命本身。\n历史规律、科学哲学内核、技术革命周期的详细定义。\n行政制度和经济政治制度变化的规律理解和周期\n能解决由内而外生内核，改习惯，升级系统、行动反馈和做事思考的整套系统框架。', contributor:'zerone · AI 出海', tags:['阅读','长期主义'], updatedAt:'2026-08-02', score:89},
  {id:13, category:'书单 / 文章 / 课程', title:'机器学习实践指南——基于 R 语言', url:'', links:[], summary:'用 R 语言把机器学习基础方法落到实践。', audience:'机器学习入门者', problem:'想理解机器学习原理，也需要知道方法如何实际应用。', reason:'最近学习机器学习的基础知识，需要用到其中的一些方法。适合初步了解机器学习原理的人，帮助我们了解机器学习有哪些方法及如何应用。', contributor:'阿圈', tags:['机器学习','R语言'], updatedAt:'2026-08-02', score:77},
  {id:14, category:'产品功能 / 产品灵感', title:'Claude Projects', url:'https://support.anthropic.com/', summary:'用项目级 Memory 与 Markdown 保持长期对话的上下文一致。', audience:'产品经理 / 长周期项目团队', problem:'项目背景不断变化，AI 容易遗忘上下文或反复要求补充资料。', reason:'在产品工作中，我比较推荐使用 Claude 的 Project 功能。产品项目通常需要持续与多个协作方沟通，需求、方案和项目进展也会不断变化。传统的单次对话容易受到上下文长度的限制，时间久了可能出现信息遗漏或需要反复补充背景的问题\n\nClaude Project 可以将项目背景、需求文档、讨论结论等内容沉淀为 Memory 或 Markdown 文档。每当项目有新的进展时，可以及时同步更新相关文档，让 AI 始终基于最新、较完整的项目上下文参与讨论。这种方式比较适合长期推进的产品项目，能够减少重复说明背景的成本，也有助于保持需求分析和方案输出的一致性', contributor:'nick · 京东 · 店铺 AI', tags:['Claude','工作流'], updatedAt:'2026-08-02', score:90},
  {id:15, category:'产品功能 / 产品灵感', title:'泛零售 AI 提效观察', url:'', links:[], summary:'围绕零售交易、搜推和即时零售的 AI 产品想法。', audience:'零售产品 / 国际化职业探索者', problem:'希望在零售业务里寻找 AI 提效机会，或讨论国际化工作路径。', reason:'泛零售相关的可Ai提效的一些观察和想法，B端为主；C端可以讨论搜推、即时零售相关的idea; 有过国外实习经验，对国际化工作感兴趣 有社群可以一起讨论', contributor:'橙子 · 京东 · 零售业务产品', tags:['零售','国际化'], updatedAt:'2026-08-02', score:83}
];
